
name: AUTO

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run check of pwd
      run: pwd
    - name: Run check of what's in pwd
      run: ls
    - name: Run a one-line script
      run: python3 todo_List.py
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.GH_TOKEN }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add .
    - name: commit changed files
      run: git commit -m "========== TB Auto updating TODO.txt"
    # - name: fetch from main
    #   run: git fetch origin main
    - name: push code to main
      # run: git push origin main
      run: git push origin HEAD:main 